In [2]:
import pandas as pd
pheno = pd.read_csv('2017heteroPheno.csv')
geno = pd.read_table('Hetero_realigned_cov10_filtered3.raw',sep="\s+")
I=pd.read_table('imputed_geno',sep="\s+")

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [77]:
X_train, X_test, y_train, y_test ,I_train,I_test= train_test_split( geno, pheno.bcw, I,test_size=0.3, random_state=214422)

# EN

In [78]:
from sklearn.linear_model import ElasticNetCV

In [79]:
regr = ElasticNetCV(cv=5, random_state=0)
regr.fit(I_train, y_train)
np.corrcoef(regr.predict(I_test),y_test)

array([[1.        , 0.14636478],
       [0.14636478, 1.        ]])

# BRR

In [80]:
from sklearn import linear_model

In [81]:
reg = linear_model.BayesianRidge()
reg.fit(I_train, y_train)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=False, tol=0.001, verbose=False)

In [82]:
np.corrcoef(reg.predict(I_test),y_test)

array([[1.       , 0.1748067],
       [0.1748067, 1.       ]])

In [83]:
np.corrcoef(reg.predict(I_train),y_train)

array([[1.        , 0.90873992],
       [0.90873992, 1.        ]])

# Ordinary Least Squares

In [84]:
reglr=linear_model.LinearRegression()
reglr.fit(I_train,y_train)
np.corrcoef(reglr.predict(I_test),y_test)

array([[1.        , 0.17519593],
       [0.17519593, 1.        ]])

# LASSO CV

In [85]:
regls = linear_model.Lasso(alpha=0.35)
regls.fit(I_train,y_train)

Lasso(alpha=0.35, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [86]:
np.corrcoef(regls.predict(I_test),y_test)

array([[1.        , 0.14221731],
       [0.14221731, 1.        ]])

# SVR

In [87]:
from sklearn.svm import SVR

In [88]:
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(I_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [89]:
svr_lin = SVR(kernel='linear')
svr_lin.fit(I_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [90]:
svr_poly = SVR(kernel='poly')
svr_poly.fit(I_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [91]:
np.corrcoef(svr_rbf.predict(I_test),y_test)

array([[1.        , 0.14469398],
       [0.14469398, 1.        ]])

In [92]:
np.corrcoef(svr_lin.predict(I_test),y_test)

array([[1.       , 0.1731401],
       [0.1731401, 1.       ]])

In [93]:
np.corrcoef(svr_poly.predict(I_test),y_test)

array([[1.        , 0.12116696],
       [0.12116696, 1.        ]])

# random forest

In [94]:
from sklearn.ensemble import RandomForestRegressor
regrf = RandomForestRegressor(n_estimators=300,max_depth=400,n_jobs=-1,random_state=0)
regrf.fit(I_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=400,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=-1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [95]:
np.corrcoef(regrf.predict(I_test),y_test)

array([[1.        , 0.15783633],
       [0.15783633, 1.        ]])

In [96]:
np.corrcoef(regrf.predict(I_train),y_train)

array([[1.       , 0.9883718],
       [0.9883718, 1.       ]])

# MLP NN

In [97]:
from sklearn.neural_network import MLPRegressor

In [98]:
regmlp=MLPRegressor(hidden_layer_sizes=400,alpha=0.001,max_iter=2000000)
regmlp.fit(I_train,y_train)

MLPRegressor(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=400, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [99]:
np.corrcoef(regmlp.predict(I_test),y_test)

array([[1.        , 0.24098522],
       [0.24098522, 1.        ]])

In [100]:
np.corrcoef(regmlp.predict(I_train),y_train)

array([[1.        , 0.63080342],
       [0.63080342, 1.        ]])